### PR TITLE
Cloning directory feature implemented

### LINKED ISSUE #10: Allow cloning projects
Allow users to clone a project directory into another directory.  This should work similar to the template feature.

Expected behavior:
1. You have a directory with a collection of files and folders
2. In StatWrap, you click "+ next to "Projects" from the main screen
3. From the list of options you select "Clone Directory"
4. StatWrap asks you to configure:
   1. The project root directory to clone (similar UI as "Existing Directory") - for the example let's say this is C:\Projects\Project1
   2. The project name (e.g., "Project2") and base directory to clone into (similar UI as "New Project") - let's say C:\Projects
5. When you click "Create Project", StatWrap should (using the example configuration from 4)
   1. Create C:\Projects\Project2
   2. Within C:\Projects\Project2, create copies of all folders in Project1.  Note that this is **only the folder structure**.  None of the files in Project1 should be copied over.  The exception is that any (per *nix standard) 'hidden' folders - those prefixed with a period - should not be be copied.  For example,  .statwrap configuration folder and .git should NOT be copied over (if they exist).
   3. Establish the .statwrap configuration folder and corresponding configuration files

In our example, if we have:
C:\Projects\Project1, with files/folders:
  * .statwrap
  * .git
  * README.md
  * docs\
      * level2\
          * MoreInfo.md
  * code\
      * python\
          * notebooks\
             * Untitled.ipynb

Then C:\Projects\Project2, at the end of the clone operation, should contain:
  * .statwrap  **This is a newly established folder, not a copy of the one from Project1**
  * docs\
      * level2\
  * code\
      * python\
          * notebooks\

### PR DESCRIPTION
**Pull request by debangi29**
Closes #10 

Allow users to clone a project directory into another directory.

image

### CODE REVIEW

File: app/utils/DirectoryCloneUtils.js [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+ */
+export const createStatWrapConfig = async (targetDir) => {
+  try {
+    const configDir = path.join(targetDir, '.statwrap');
+    fs.mkdirSync(configDir, { recursive: true });
+    
+    // Create basic configuration files
+    // This is just a placeholder - you'll need to implement the actual config creation
+    // based on how StatWrap creates config files for new projects
+    const configFile = path.join(configDir, 'config.json');
```
Comment (lrasmus) [inline app/utils/DirectoryCloneUtils.js:62]: I'm wondering why we would create this file instead of the actual .statwrap-project.json.  This will leave an extra file around that is not usable.  Would it be possible to create a bare minimum .statwrap-project.json file instead?

File: app/utils/DirectoryCloneUtils.js [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+/**
+ * Creates a new StatWrap configuration folder in the target directory
+ * 
+ * @param {string} targetDir - The target directory where the .statwrap folder will be created
+ * @returns {Promise<void>}
+ */
+export const createStatWrapConfig = async (targetDir) => {
+  try {
+    const configDir = path.join(targetDir, '.statwrap');
```
Comment (lrasmus) [inline app/utils/DirectoryCloneUtils.js:56]: Please use constants instead of `'.statwrap'`.

File: app/main.dev.js [hunk 3]
```diff
@@ -443,11 +451,37 @@ ipcMain.on(Messages.CREATE_PROJECT_REQUEST, async (event, project) => {
...
+            
+            // Create the StatWrap configuration
+            await createStatWrapConfig(validationReport.project.path, validationReport.project.id, validationReport.project.name);
+            
+            // Create a marker file to identify this as a cloned project
+            const statWrapDir = path.join(validationReport.project.path, Constants.StatWrapFiles.BASE_FOLDER);
+            if (!fs.existsSync(statWrapDir)) {
+              fs.mkdirSync(statWrapDir, { recursive: true });
+            }
+            fs.writeFileSync(path.join(statWrapDir, 'cloned_project_marker'), 'This is a cloned project');
```
Comment (lrasmus) [inline app/main.dev.js:477]: In the cloned_project_marker file, could we add some additional information?  Specifically I'm thinking of the project path that this was cloned from.

**Review by lrasmus — CHANGES_REQUESTED** [review]
Excellent work - I do have a few questions/changes to ask for.  Please let me know if you have any questions or if there's anything I can clarify further.

File: app/containers/CreateProjectDialog/CreateProjectDialog.js [hunk 4]
```diff
@@ -101,38 +105,108 @@ class CreateProjectDialog extends Component {
...
+  }
+  
+  validateCloneDirectories(sourceDir, targetBaseDir, name) {
+    const hasRequiredFields = sourceDir && sourceDir !== '' && 
+           targetBaseDir && targetBaseDir !== '' && 
+           name && name !== '';
+    
+    if (!hasRequiredFields) return { isValid: false, errorMessage: null };
+    // Check if user is trying to clone a directory onto itself
+    if (sourceDir === targetBaseDir) {
```
Comment (lrasmus) [inline app/containers/CreateProjectDialog/CreateProjectDialog.js:154]: The validation checks are great!  I think there's just one more scenario to handle:
```
sourceDir = '/my/path/dir1'
targetBaseDir = '/my/path'
name = 'dir1'
```
Check here that `targetBaseDir` joined with `name` is not the same path as `sourceDir`.

File: app/utils/DirectoryCloneUtils.js [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+ * 
+ * @param {string} targetDir - The target directory where the StatWrap project file will be created
+ * @returns {Promise<void>}
+ */
+export const createStatWrapConfig = async (targetDir) => {
+  try {
+    const configDir = path.join(targetDir, Constants.StatWrapFiles.BASE_FOLDER);
+    fs.mkdirSync(configDir, { recursive: true });
+    
+    const projectConfigFile = path.join(targetDir, Constants.StatWrapFiles.PROJECT);
```
Comment (lrasmus) [inline app/utils/DirectoryCloneUtils.js:60]: Just realized this was going to `targetDir`, but it should go to `configDir`

**Review by lrasmus — CHANGES_REQUESTED** [review]
The changes are great!!  Just two minor fixes requested.

**Comment by lrasmus** [comment]
Thank you @debangi29 for all of your hard work on this!
